<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260913083000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create encrypted webhook registry and transactional webhook delivery outbox.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
CREATE TABLE webhook_endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id VARCHAR(35) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    enabled BOOLEAN NOT NULL,
    starts_after_event_id BIGINT NOT NULL,
    secret_ciphertext TEXT NOT NULL,
    secret_nonce VARCHAR(64) NOT NULL,
    secret_algorithm VARCHAR(64) NOT NULL,
    secret_key_version SMALLINT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE UNIQUE INDEX uniq_webhook_endpoint_public_id
ON webhook_endpoint (public_id)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE TABLE webhook_endpoint_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    webhook_endpoint_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    PRIMARY KEY(id)
)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE UNIQUE INDEX uniq_webhook_endpoint_subscription
ON webhook_endpoint_subscription (
    webhook_endpoint_id,
    event_type
)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE INDEX idx_webhook_subscription_event
ON webhook_endpoint_subscription (
    event_type,
    webhook_endpoint_id
)
SQL
        );

        $this->addSql(
            <<<'SQL'
ALTER TABLE webhook_endpoint_subscription
ADD CONSTRAINT fk_webhook_subscription_endpoint
FOREIGN KEY (webhook_endpoint_id)
REFERENCES webhook_endpoint (id)
ON DELETE CASCADE
NOT DEFERRABLE
INITIALLY IMMEDIATE
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE TABLE webhook_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id VARCHAR(36) NOT NULL,
    webhook_endpoint_id BIGINT NOT NULL,
    outbound_message_event_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count SMALLINT NOT NULL,
    queued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    next_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    succeeded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    last_error VARCHAR(512) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE UNIQUE INDEX uniq_webhook_delivery_public_id
ON webhook_delivery (public_id)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE UNIQUE INDEX uniq_webhook_delivery_event_endpoint
ON webhook_delivery (
    webhook_endpoint_id,
    outbound_message_event_id
)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE INDEX idx_webhook_delivery_pending
ON webhook_delivery (
    status,
    next_attempt_at,
    queued_at,
    id
)
SQL
        );

        $this->addSql(
            <<<'SQL'
ALTER TABLE webhook_delivery
ADD CONSTRAINT fk_webhook_delivery_endpoint
FOREIGN KEY (webhook_endpoint_id)
REFERENCES webhook_endpoint (id)
ON DELETE RESTRICT
NOT DEFERRABLE
INITIALLY IMMEDIATE
SQL
        );

        $this->addSql(
            <<<'SQL'
ALTER TABLE webhook_delivery
ADD CONSTRAINT fk_webhook_delivery_event
FOREIGN KEY (outbound_message_event_id)
REFERENCES outbound_message_event (id)
ON DELETE CASCADE
NOT DEFERRABLE
INITIALLY IMMEDIATE
SQL
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql(
            'DROP TABLE webhook_delivery'
        );

        $this->addSql(
            'DROP TABLE webhook_endpoint_subscription'
        );

        $this->addSql(
            'DROP TABLE webhook_endpoint'
        );
    }
}
