<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912222500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create immutable outbound message event history and backfill existing transitions.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
CREATE TABLE outbound_message_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    outbound_message_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL
        );

        $this->addSql(
            <<<'SQL'
CREATE INDEX idx_outbound_message_event_timeline
ON outbound_message_event (
    outbound_message_id,
    occurred_at,
    id
)
SQL
        );

        $this->addSql(
            <<<'SQL'
ALTER TABLE outbound_message_event
ADD CONSTRAINT fk_outbound_message_event_message
FOREIGN KEY (outbound_message_id)
REFERENCES outbound_message (id)
ON DELETE CASCADE
NOT DEFERRABLE
INITIALLY IMMEDIATE
SQL
        );

        $this->addSql(
            <<<'SQL'
INSERT INTO outbound_message_event (
    outbound_message_id,
    event_type,
    occurred_at
)
SELECT
    id,
    'queued',
    created_at
FROM outbound_message
SQL
        );

        $this->addSql(
            <<<'SQL'
INSERT INTO outbound_message_event (
    outbound_message_id,
    event_type,
    occurred_at
)
SELECT
    id,
    'ready_for_submission',
    ready_for_submission_at
FROM outbound_message
WHERE ready_for_submission_at IS NOT NULL
SQL
        );

        $this->addSql(
            <<<'SQL'
INSERT INTO outbound_message_event (
    outbound_message_id,
    event_type,
    occurred_at
)
SELECT
    id,
    'submitting',
    submitting_at
FROM outbound_message
WHERE submitting_at IS NOT NULL
SQL
        );

        $this->addSql(
            <<<'SQL'
INSERT INTO outbound_message_event (
    outbound_message_id,
    event_type,
    occurred_at
)
SELECT
    id,
    'submission_uncertain',
    submission_uncertain_at
FROM outbound_message
WHERE submission_uncertain_at IS NOT NULL
SQL
        );

        $this->addSql(
            <<<'SQL'
INSERT INTO outbound_message_event (
    outbound_message_id,
    event_type,
    occurred_at
)
SELECT
    id,
    'submitted',
    submitted_at
FROM outbound_message
WHERE submitted_at IS NOT NULL
SQL
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql(
            'DROP TABLE outbound_message_event'
        );
    }
}
