enabled = true;

allow_envfrom_empty = false;
allow_hdrfrom_mismatch = false;
allow_hdrfrom_multiple = false;
allow_username_mismatch = false;

sign_authenticated = false;
sign_local = true;

try_fallback = false;

use_domain = "header";
use_esld = false;
use_redis = false;

domain {
    heymail.test {
        selectors [
            {
                path = "/run/heymail-dkim/heymail.test.lab.key";
                selector = "lab";
            }
        ]
    }
}
