enabled = true;

HEYMAIL_INBOUND {
    id = "heymail_inbound";
    priority = high;

    request_header = {
        "MTA-Name" = "^INBOUND$";
    }

    apply {
        symbols_disabled = [
            "FORCE_ACTION_REQUIRE_DKIM_SIGNATURE"
        ];
    }
}
