framework:
    messenger:
        failure_transport: failed

        transports:
            outbound:
                dsn: 'doctrine://default'
                options:
                    table_name: messenger_messages
                    queue_name: outbound
                    auto_setup: false

                retry_strategy:
                    max_retries: 5
                    delay: 5000
                    multiplier: 2
                    max_delay: 60000

            failed:
                dsn: 'doctrine://default'
                options:
                    table_name: messenger_messages
                    queue_name: failed
                    auto_setup: false
