framework:
    messenger:
        failure_transport: failed

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        routing:
            'App\Message\SendOutboundEmail': outbound
            'App\Message\DeliverWebhook': webhook_delivery
            'App\Message\VerifySendingDomain': domain_verification
            'App\Message\ProvisionSendingDomainDkim': dkim_provisioning

        transports:
            outbound:
                dsn: 'doctrine://default'
                serializer: messenger.transport.symfony_serializer
                options:
                    table_name: messenger_messages
                    queue_name: outbound
                    auto_setup: false

                retry_strategy:
                    max_retries: 5
                    delay: 5000
                    multiplier: 2
                    max_delay: 60000

            domain_verification:
                dsn: 'doctrine://default'
                serializer: messenger.transport.symfony_serializer
                options:
                    table_name: messenger_messages
                    queue_name: domain_verification
                    auto_setup: false

                retry_strategy:
                    max_retries: 3
                    delay: 2000
                    multiplier: 2
                    max_delay: 10000


            dkim_provisioning:
                dsn: 'doctrine://default'
                serializer: messenger.transport.symfony_serializer
                options:
                    table_name: messenger_messages
                    queue_name: dkim_provisioning
                    auto_setup: false

                retry_strategy:
                    max_retries: 3
                    delay: 2000
                    multiplier: 2
                    max_delay: 10000

            webhook_delivery:
                dsn: 'doctrine://default'
                serializer: messenger.transport.symfony_serializer
                options:
                    table_name: messenger_messages
                    queue_name: webhook_delivery
                    auto_setup: false

                retry_strategy:
                    max_retries: 0


            failed:
                dsn: 'doctrine://default'
                serializer: messenger.transport.symfony_serializer
                options:
                    table_name: messenger_messages
                    queue_name: failed
                    auto_setup: false
